### ISSUE TITLE
Use Rojo so that people can edit code directly

### ISSUE THREAD

**Issue by Nickanda** [myCenterRBLX/Loader#1]
The Roblox model file should still be made available in the event that someone wants to make changes to the GUI but Rojo should also be used so that people can edit the code directly without having to download the RBXM file.

This alleviates the pain of having to look through the RBXM file each time there is a new update. After all, the purpose of Github is to collaboratively edit the code and not the GUIs.

**Comment by mwalden2004** [comment]
open a pull request mr developer

**Comment by Nickanda** [comment]
Will do after my AP exams are completed tomorrow

**Comment by mwalden2004** [comment]
Sounds good, thank you.

**Comment by 9harrisonc** [comment]
Just testing leaving a comment - ignore this.

**Comment by mwalden2004** [comment]
Pull request has solved this issue, pushed yesterday.
